package com.mycompany.app;

/**
 *This is autogenerated file from framework and just kept as a stub inorder to perform dev testing.
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        System.out.println( "Hello World!" );
    }
}
